CREATE DATABASE `assignment` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE DATABASE `assignment_prod` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE DATABASE `assignment_uat` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE DATABASE `assignement_qa` /*!40100 DEFAULT CHARACTER SET utf8 */;